sudo: required
services:
  - docker

before_install:
  - docker build -t razaamir/docker-springboot-poc -f Dockerfile .

script:
  - docker run -e CI=true razaamir/docker-springboot-poc

#deploy:
#  provider: elasticbeanstalk
#  region: eu-west-2
#  app: "docker-react"
#  env: "DockerReact-env"
#  bucket_name: "elasticbeanstalk-eu-west-2-424038938249"
#  bucket_path: "docker-react"
#  on:
#    branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key: $AWS_SECRET_KEY


